### ISSUE TITLE
Python solution - chapter 01 - ex 07

### ISSUE THREAD

**Issue by yuriaps** [alexhagiopol/ctci#61]
import numpy as np           <----- import numpy 
import math

def rotate_matrix(matrix):
    # assume clockwise rotation
    matrix = np.array(matrix)
    N, M = matrix.shape                                  <------ doesn't work without numpy
    assert(N == M)  # must be NxN matrix
    for l in range (int(math.floor(N/2))):         <------- need to cast int 
        for i in range(l, N - 1 - l):
            # from top row to right colum
                .
                .
                .

**Comment by alexhagiopol** [comment]
Thanks for this message. If you want to contribute changes to the repo, please provide a pull request. Issues is not the right mechanism.

Furthermore, I'm not convinced these changes are necessary because the tests do not fail. Please contribute a test to tests.py that would fail with the code as is to illustrate why the changes are necessary.
